version: "3"

volumes:
  shared-logs:

  # Per application services
  storage-mysql:
  storage-postgresql:
  storage-influxdb:
  storage-redis:
  storage-consul:
  storage-jenkins:
  storage-gitlab:
  storage-elasticsearch:
  storage-kapacitor:
  storage-kibana:
  storage-grafana:
  storage-chronograf:

services:

  # ---------------------------------------------------------------------------
  #  MySQL Database 
  # ---------------------------------------------------------------------------
  mysql:
    build:
      context: services/mysql
      args:
        MYSQL_VERSION: latest
    dns_search: labs
    hostname: mysql.labs
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: meinelabs-passwd
    volumes:
      - storage-mysql:/var/lib/mysql:rw
      - shared-logs:/var/log/mysql:rw

  # ---------------------------------------------------------------------------
  #  PostgreSQL Database 
  # ---------------------------------------------------------------------------
  postgres:
    build:
      context: services/postgres
      args:
        POSTGRES_VERSION: latest
    dns_search: labs
    hostname: postgres.labs
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: meinelabs-passwd
    volumes:
      - storage-postgresql:/var/lib/postgresql/:rw
      - shared-logs:/var/logs/postgres:rw

  # ---------------------------------------------------------------------------
  #  InfluxDB Database
  # ---------------------------------------------------------------------------
  influxdb:
    build:
      context: services/influxdb
      args:
        INFLUXDB_VERSION: latest
    dns_search: labs
    hostname: influxdb.labs
    ports:
      - "8082:8082"
      - "8088:8088"
      - "8089:8089/udp"
    volumes:
      - ./services/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
      - storage-influxdb:/var/lib/influxdb:rw

  # ---------------------------------------------------------------------------
  #  Jenkins Service
  # ---------------------------------------------------------------------------
  memcached:
    build:
      context: services/memcached
      args:
        MEMCACHED_VERSION: latest
    dns_search: labs
    hostname: memcached.labs
    ports:
      - "11211:11211"
    volumes:
      - shared-logs:/var/log/memcached:rw

  # ---------------------------------------------------------------------------
  #  Redis Service
  # ---------------------------------------------------------------------------
  redis:
    build:
      context: services/redis
      args:
        REDIS_VERSION: latest
    dns_search: labs
    hostname: redis.labs
    command:
      - redis-server
      - /usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    volumes:
      - ./services/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
      - storage-redis:/data:rw 
      - shared-logs:/var/log/redis:rw

  # ---------------------------------------------------------------------------
  #  Consul Service
  # ---------------------------------------------------------------------------
  consul:
    build:
      context: services/consul
      args:
        CONSUL_VERSION: latest
    dns_search: labs
    hostname: consul.redis
    ports:
      - "8300:8300"
      - "8301:8301"
      - "8302:8302/tcp"
      - "8302:8302/udp"
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    volumes:
      - ./services/consul/consul.json:/consul/config/consul.json:ro
      - storage-consul:/consul/data:rw
      - shared-logs:/var/log/consul:rw 

  # ---------------------------------------------------------------------------
  #  Jenkins Service
  # ---------------------------------------------------------------------------
  jenkins:
    build:
      context: services/jenkins
      args:
        JENKINS_VERSION: lts
    dns_search: labs
    hostname: jenkins.labs
    ports:
      - "8080:8080"
    volumes:
      - storage-jenkins:/var/jenkins_home:rw
      - shared-logs:/mnt/logs:rw

  # ---------------------------------------------------------------------------
  #  Gitlab Service 
  # ---------------------------------------------------------------------------
  gitlab:
    build:
      context: services/gitlab
      args:
        GITLAB_VERSION: latest
    dns_search: labs
    hostname: gitlab.labs
    ports:
      - "8090:80"
      - "8091:443"
      - "8092:22"
    volumes:
      - storage-gitlab:/etc/gitlab:rw
      - storage-gitlab://var/opt/gitlab:rw
      - shared-logs:/var/log/gitlab:rw

  # ---------------------------------------------------------------------------
  #  Elasticsearch Service 
  # ---------------------------------------------------------------------------
  elasticsearch:
    build:
      context: services/elasticsearch
      args:
        ELASTICSEARCH_VERSION: 6.5.0
    dns_search: labs
    hostname: elasticsearch.labs
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./services/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/elasticsearch.yml:ro
      - storage-elasticsearch:/usr/share/elasticsearch/lib:rw
      - shared-logs:/usr/share/elasticsearch/logs:rw

  # ---------------------------------------------------------------------------
  #  Logstash Service
  # ---------------------------------------------------------------------------
  logstash:
    build:
      context: services/logstash/
      args:
        LOGSTASH_VERSION: 6.7.0
    dns_search: labs
    hostname: logstash.labs
    ports:
      - "5000:5000"
      - "9600:9600"
    volumes:
      - ./services/logstash/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./services/logstash/pipeline:/usr/share/logstash/pipeline:ro

  # ---------------------------------------------------------------------------
  #  Kapacitor Service
  # ---------------------------------------------------------------------------
  kapacitor:
    build:
      context: services/kapacitor
      args:
        KAPACITOR_VERSION: latest
    dns_search: labs
    hostname: kapacitor.labs
    ports:
      - "9092:9092"
    volumes:
      - ./services/kapacitor/kapacitor.conf:/etc/kapacitor/kapacitor.conf:ro
      - storage-kapacitor:/var/lig/kapacitor:rw
      - shared-logs:/var/log/kapacitor:rw
    depends_on:
      - influxdb

  # ---------------------------------------------------------------------------
  #  Telegraf Service
  # ---------------------------------------------------------------------------
  telegraf:
    build:
      context: services/telegraf
      args:
        TELEGRAF_VERSION: latest
    dns_search: labs
    hostname: telegraf.labs
    volumes:
      - ./services/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock:rw
    depends_on:
      - influxdb

  # ---------------------------------------------------------------------------
  #  Kibana Service 
  # ---------------------------------------------------------------------------
  kibana:
    build:
      context: services/kibana
      args:
        KIBANA_VERSION: 6.5.0
    dns_search: labs
    hostname: kibana.labs
    ports:
      - "5601:5601"
    volumes:
      - ./services/kibana/kibana.yml:/usr/share/kibana/kibana.yml:ro
      - storage-kibana:/usr/share/kibana/lib:rw
      - shared-logs:/usr/share/kibana/logs:rw
    depends_on:
      - elasticsearch

  # ---------------------------------------------------------------------------
  #  Grafana Service
  # ---------------------------------------------------------------------------
  grafana:
    build:
      context: services/grafana
      args:
        GRAFANA_VERSION: latest
    dns_search: labs
    hostname: grafana.labs
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: meinelabs-passwd
    volumes:
      - storage-grafana:/var/lib/grafana:rw
      - shared-logs:/var/log/grafana:rw

  # ---------------------------------------------------------------------------
  #  Chronograf Service
  # ---------------------------------------------------------------------------
  chronograf:
    build:
      context: services/chronograf
      args:
        CHRONOGRAF_VERSION: latest
    dns_search: labs
    hostname: crhonograf.labs
    ports:
      - "8888:8888"
    command:
      - chronograf
      - "--port=8888"
      - "--influxdb-url=http://influxdb:8086"
      - "--kapacitor-url=http://kapacitor:9092"
    volumes:
      - storage-chronograf:/var/lib/chronograf:rw
      - shared-logs:/var/log/chronograf:rw
    depends_on:
      - influxdb
      - kapacitor

  # ---------------------------------------------------------------------------
  #  Nginx Service 
  # ---------------------------------------------------------------------------
  nginx:
    build:
      context: services/nginx
      args:
        NGINX_VERSION: latest
    dns_search: labs
    hostname: nginx.labs
    ports:
      - "80:80"
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./services/nginx/conf.d:/etc/nginx/conf.d:rw
      - shared-logs:/var/log/nginx:rw
